CREATE DATABASE AVIATION_DB;
USE DATABASE AVIATION_DB;
CREATE SCHEMA RAW;
CREATE SCHEMA MART;
CREATE WAREHOUSE AVIATION_WH
WITH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;
USE WAREHOUSE AVIATION_WH;
USE SCHEMA RAW;
CREATE OR REPLACE TABLE PASSENGER (
PASSENGER_ID INT,
PASSENGER_NAME STRING,
PASSPORT_NUMBER STRING,
NATIONALITY STRING,
PASSENGER_TYPE STRING
);
CREATE OR REPLACE TABLE FLIGHT (
FLIGHT_ID INT,
AIRLINE_NAME STRING,
SOURCE_AIRPORT STRING,
DESTINATION_AIRPORT STRING,
FLIGHT_STATUS STRING
);
CREATE OR REPLACE TABLE BOOKING (
BOOKING_ID INT,
PASSENGER_ID INT,
FLIGHT_ID INT,
BOOKING_AMOUNT FLOAT,
BOOKING_DATE DATE,
BOOKING_STATUS STRING
);
CREATE OR REPLACE TABLE BAGGAGE (
BAGGAGE_ID INT,
BOOKING_ID INT,
BAGGAGE_WEIGHT FLOAT,
BAGGAGE_STATUS STRING,
CHECKEDIN_AT TIMESTAMP
);
CREATE OR REPLACE TABLE DELAY_ALERT (
ALERT_ID INT,
FLIGHT_ID INT,
DELAY_REASON STRING,
DELAY_DURATION INT,
ALERT_STATUS STRING
);
USE SCHEMA RAW;
DROP TABLE IF EXISTS PASSENGER;
DROP TABLE IF EXISTS FLIGHT;
DROP TABLE IF EXISTS BOOKING;
DROP TABLE IF EXISTS BAGGAGE;
DROP TABLE IF EXISTS DELAY_ALERT;

CREATE OR REPLACE STAGE AVIATION_STAGE;
CREATE OR REPLACE TABLE PASSENGER (
PASSENGER_ID INT,
PASSENGER_NAME STRING,
PASSPORT_NUMBER STRING,
NATIONALITY STRING,
PASSENGER_TYPE STRING
);
CREATE OR REPLACE TABLE FLIGHT (
FLIGHT_ID INT,
AIRLINE_NAME STRING,
SOURCE_AIRPORT STRING,
DESTINATION_AIRPORT STRING,
FLIGHT_STATUS STRING
);
CREATE OR REPLACE TABLE BOOKING (
BOOKING_ID INT,
PASSENGER_ID INT,
FLIGHT_ID INT,
BOOKING_AMOUNT FLOAT,
BOOKING_DATE DATE,
BOOKING_STATUS STRING
);
CREATE OR REPLACE TABLE BAGGAGE (
BAGGAGE_ID INT,
BOOKING_ID INT,
BAGGAGE_WEIGHT FLOAT,
BAGGAGE_STATUS STRING,
CHECKEDIN_AT TIMESTAMP
);
CREATE OR REPLACE TABLE DELAY_ALERT (
ALERT_ID INT,
FLIGHT_ID INT,
DELAY_REASON STRING,
DELAY_DURATION INT,
ALERT_STATUS STRING
);



