use database aviation_db;
SELECT
P.PASSENGER_NAME,
P.NATIONALITY,
F.AIRLINE_NAME,
F.SOURCE_AIRPORT,
F.DESTINATION_AIRPORT,
B.BOOKING_AMOUNT,
B.BOOKING_DATE,
B.BOOKING_STATUS
FROM MART.FACT_BOOKING B
JOIN MART.DIM_PASSENGER P
ON B.PASSENGER_ID = P.PASSENGER_ID
JOIN MART.DIM_FLIGHT F
ON B.FLIGHT_ID = F.FLIGHT_ID;


-- REVENUE ANALYSIS

SELECT
F.AIRLINE_NAME,
COUNT(B.BOOKING_ID) AS TOTAL_BOOKINGS,
SUM(B.BOOKING_AMOUNT) AS TOTAL_REVENUE
FROM MART.FACT_BOOKING B
JOIN MART.DIM_FLIGHT F
ON B.FLIGHT_ID = F.FLIGHT_ID
GROUP BY F.AIRLINE_NAME
ORDER BY TOTAL_REVENUE DESC;
