USE DATABASE AVIATION_DB;
USE SCHEMA MART;
CREATE OR REPLACE TABLE DIM_PASSENGER AS
SELECT
PASSENGER_ID,
PASSENGER_NAME,
PASSPORT_NUMBER,
NATIONALITY,
PASSENGER_TYPE
FROM AVIATION_DB.RAW.PASSENGER;
CREATE OR REPLACE TABLE DIM_FLIGHT AS
SELECT
FLIGHT_ID,
AIRLINE_NAME,
SOURCE_AIRPORT,
DESTINATION_AIRPORT,
FLIGHT_STATUS
FROM AVIATION_DB.RAW.FLIGHT;
CREATE OR REPLACE TABLE FACT_BOOKING AS
SELECT
BOOKING_ID,
PASSENGER_ID,
FLIGHT_ID,
BOOKING_AMOUNT,
BOOKING_DATE,
BOOKING_STATUS
FROM AVIATION_DB.RAW.BOOKING;