USE DATABASE AVIATION_DB;
USE SCHEMA RAW;
CREATE OR REPLACE STREAM BOOKING_STREAM
ON TABLE BOOKING;
SELECT * FROM BOOKING_STREAM;
CREATE OR REPLACE TASK BOOKING_TASK
WAREHOUSE = AVIATION_WH
SCHEDULE = '1 MINUTE'
AS
INSERT INTO MART.FACT_BOOKING
SELECT
BOOKING_ID,
PASSENGER_ID,
FLIGHT_ID,
BOOKING_AMOUNT,
BOOKING_DATE,
BOOKING_STATUS
FROM BOOKING_STREAM;
USE SCHEMA MART;
CREATE OR REPLACE DYNAMIC TABLE REVENUE_SUMMARY
TARGET_LAG = '1 minute'
WAREHOUSE = AVIATION_WH
AS
SELECT
F.AIRLINE_NAME,
COUNT(B.BOOKING_ID) AS TOTAL_BOOKINGS,
SUM(B.BOOKING_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BOOKING B
JOIN DIM_FLIGHT F
ON B.FLIGHT_ID = F.FLIGHT_ID
GROUP BY F.AIRLINE_NAME;
SELECT * FROM REVENUE_SUMMARY;